/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_JNI */

#ifndef _Included_ece596_ucsb_localizedwifi_JNI
#define _Included_ece596_ucsb_localizedwifi_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_JNI
 * Method:    getCInt
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_ece596_ucsb_localizedwifi_JNI_getCInt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
